<a href="https://colab.research.google.com/github/KayalvizhiT513/TNEA-cutoff-trend-analysis/blob/main/General_vs_7_5_Reservation_(Data_Preprocessing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# üß∞ 1. Data Acquisition
*Objective: Extract, access, and organize raw data*

## üì¶ 1.1. Setup & Dependencies

In [ ]:
!pip install tabula-py pandas

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 12.0/12.0 MB 21.8 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0

In [ ]:

!apt-get install -y openjdk-11-jre-headless  # Java runtime required by tabula-py

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openjdk-11-jre-headless is already the newest version (11.0.27+6~us1-0ubuntu1~22.04).
openjdk-11-jre-headless set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.

In [ ]:
import os
import tabula
import pandas as pd
from google.colab import drive

## üîó 1.2. Google Drive Mounting

In [ ]:
# Mount Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## üì• 1.3. Extract Tables from PDFs (Bulk to Excel)
*Loop through and extract all tables from PDFs in a folder.*

In [ ]:

# Path to your Google Drive folder containing PDFs (change this)
folder_path = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff'  # <-- update this path

# Output folder for Excel files (optional: create a subfolder)
output_folder = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff'
os.makedirs(output_folder, exist_ok=True)

# List all PDF files in the folder
pdf_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.pdf')]

print(f"Found {len(pdf_files)} PDF files.")

Found 9 PDF files.

In [ ]:

# Loop through each PDF and convert to Excel
for pdf_file in pdf_files:
    pdf_path = os.path.join(folder_path, pdf_file)
    print(f"Processing: {pdf_file}")

    try:
        # Extract tables from PDF
        dfs = tabula.read_pdf(pdf_path, pages='all', multiple_tables=True)

        # Combine all extracted tables into one DataFrame
        combined_df = pd.concat(dfs, ignore_index=True)

        # Save as Excel file
        excel_filename = os.path.splitext(pdf_file)[0] + '.xlsx'
        excel_path = os.path.join(output_folder, excel_filename)
        combined_df.to_excel(excel_path, index=False)

        print(f"Saved Excel: {excel_path}")

    except Exception as e:
        print(f"Failed to process {pdf_file}: {e}")

print("All done!")

WARNING:tabula.backend:Failed to import jpype dependencies. Fallback to subprocess.
WARNING:tabula.backend:No module named 'jpype'

Processing: GOVT_ACADEMIC_ROUND1_2024.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND1_2024.xlsx
Processing: GOVT_ACADEMIC_ROUND3_2024.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND3_2024.xlsx
Processing: GOVT_ACADEMIC_ROUND2_2024.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND2_2024.xlsx
Processing: GOVT_ACADEMIC_ROUND1_2023.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND1_2023.xlsx
Processing: GOVT_ACADEMIC_ROUND2_2023.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND2_2023.xlsx
Processing: GOVT_ACADEMIC_ROUND3_2023.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND3_2023.xlsx
Processing: GOVT_ACADEMIC_ROUND1_2022.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND1_2022.xlsx
Processing: GOVT_ACADEMIC_ROUND2_2022.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND2_2022.xlsx
Processing: GOVT_ACADEMIC_ROUND3_2022.pdf
Saved Excel: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND3_2022.xlsx
All done!

In [ ]:
# Extract tables from PDF
dfs = tabula.read_pdf('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND4_2022.pdf', pages='all', multiple_tables=True)

# Combine all extracted tables into one DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

# Save as Excel file
combined_df.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND4_2022.xlsx', index=False)

print(f"Saved Excel")

Saved Excel

# üßπ 2. Data Cleaning & Preprocessing
*Objective: Convert messy or inconsistent raw data into structured format*

## üíß 2.1. Drop empty columns
*Filtering non-numeric rows, dropping NaNs, resetting index.*

In [ ]:
# Load the Excel file
file_path = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND4_2022.xlsx'  # Replace with your actual file path
df = pd.read_excel(file_path)

df.head()

,S NO,APPLN\rNO,NAME OF THE CANDIDATE,DOB,COMMU\rNITY,AGGR\rMARK,GENERAL\rRANK,GOVT\rRANK,COLLEGE\rCODE,BRANCH\rCODE,ALLOTTED\rCATEGORY
0,1,352308,SHAKTHISHALINI S,26-03-2005,BC,171.50,32354,1290,2634,IT,BC
1,2,337932,KEERTHIKA S,09-11-2005,MBC,161.00,48500,2686,2762,EC,OC
2,3,294895,TAMILAMUDHAN V,03-01-2004,SC,160.99,48646,2699,1325,ME,OC
3,4,222601,vishnupritha,24-09-2005,OC,159.00,51472,2940,2345,AG,OC
4,5,229092,MAHALAKSHMI M,17-08-2004,BC,158.50,52407,3035,3908,CS,BC

In [ ]:
df

,S NO,APPLN\rNO,NAME OF THE CANDIDATE,DOB,COMMU\rNITY,AGGR\rMARK,GENERAL\rRANK,GOVT\rRANK,COLLEGE\rCODE,BRANCH\rCODE,ALLOTTED\rCATEGORY
0,1,352308,SHAKTHISHALINI S,26-03-2005,BC,171.50,32354,1290,2634,IT,BC
1,2,337932,KEERTHIKA S,09-11-2005,MBC,161.00,48500,2686,2762,EC,OC
2,3,294895,TAMILAMUDHAN V,03-01-2004,SC,160.99,48646,2699,1325,ME,OC
3,4,222601,vishnupritha,24-09-2005,OC,159.00,51472,2940,2345,AG,OC
4,5,229092,MAHALAKSHMI M,17-08-2004,BC,158.50,52407,3035,3908,CS,BC
...,...,...,...,...,...,...,...,...,...,...,...
3655,3656,268654,CHANDHURU R M,12-07-2005,BC,80.00,156066,22011,4946,CS,BC
3656,3657,333602,S.dhanushraj,14-12-2004,BC,80.00,156111,22025,3819,IC,OC
3657,3658,402708,BALAMURUGAN G,01-04-2005,MBC,79.50,156205,22067,4943,ME,OC
3658,3659,336512,ADITHYA S,29-08-2005,SC,78.50,156253,22088,3810,ME,SC
3659,3660,243612,SAKTHIVEL S,12-01-2004,BC,78.00,156268,22094,1421,CE,BC

In [ ]:
# Identify the first column (by index)
first_col = df.columns[0]

# Keep only rows where the first column is numeric
df_clean = df[pd.to_numeric(df[first_col], errors='coerce').notna()]

# Remove columns where all values are NaN
df_clean = df_clean.dropna(axis=1, how='all')

# Optionally, reset index
df_clean = df_clean.reset_index(drop=True)

df_clean

,S NO,APPLN\rNO,NAME OF THE CANDIDATE,DOB,COMMU\rNITY,AGGR\rMARK,GENERAL\rRANK,GOVT\rRANK,COLLEGE\rCODE,BRANCH\rCODE,ALLOTTED\rCATEGORY
0,1,352308,SHAKTHISHALINI S,26-03-2005,BC,171.50,32354,1290,2634,IT,BC
1,2,337932,KEERTHIKA S,09-11-2005,MBC,161.00,48500,2686,2762,EC,OC
2,3,294895,TAMILAMUDHAN V,03-01-2004,SC,160.99,48646,2699,1325,ME,OC
3,4,222601,vishnupritha,24-09-2005,OC,159.00,51472,2940,2345,AG,OC
4,5,229092,MAHALAKSHMI M,17-08-2004,BC,158.50,52407,3035,3908,CS,BC
...,...,...,...,...,...,...,...,...,...,...,...
3655,3656,268654,CHANDHURU R M,12-07-2005,BC,80.00,156066,22011,4946,CS,BC
3656,3657,333602,S.dhanushraj,14-12-2004,BC,80.00,156111,22025,3819,IC,OC
3657,3658,402708,BALAMURUGAN G,01-04-2005,MBC,79.50,156205,22067,4943,ME,OC
3658,3659,336512,ADITHYA S,29-08-2005,SC,78.50,156253,22088,3810,ME,SC
3659,3660,243612,SAKTHIVEL S,12-01-2004,BC,78.00,156268,22094,1421,CE,BC

## üßæ 2.2. Column Renaming
*Standardizing column names for consistency.*

In [ ]:
# Rename columns
new_column_names = [
    "S NO", "APPLN NUMBER", "NAME OF THE CANDIDATE", "DOB", "COMMUNITY",
    "AGGR MARK", "GENERAL RANK", "GOVT RANK", "COLLEGE CODE", "BRANCH CODE", "ALLOTTED CATEGORY"
]

# Only rename if number of columns match
if len(df_clean.columns) >= len(new_column_names):
    df_clean.columns = new_column_names + list(df_clean.columns[len(new_column_names):])
else:
    raise ValueError("Not enough columns in the file to rename properly.")

df_clean

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,DOB,COMMUNITY,AGGR MARK,GENERAL RANK,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY
0,1,352308,SHAKTHISHALINI S,26-03-2005,BC,171.50,32354,1290,2634,IT,BC
1,2,337932,KEERTHIKA S,09-11-2005,MBC,161.00,48500,2686,2762,EC,OC
2,3,294895,TAMILAMUDHAN V,03-01-2004,SC,160.99,48646,2699,1325,ME,OC
3,4,222601,vishnupritha,24-09-2005,OC,159.00,51472,2940,2345,AG,OC
4,5,229092,MAHALAKSHMI M,17-08-2004,BC,158.50,52407,3035,3908,CS,BC
...,...,...,...,...,...,...,...,...,...,...,...
3655,3656,268654,CHANDHURU R M,12-07-2005,BC,80.00,156066,22011,4946,CS,BC
3656,3657,333602,S.dhanushraj,14-12-2004,BC,80.00,156111,22025,3819,IC,OC
3657,3658,402708,BALAMURUGAN G,01-04-2005,MBC,79.50,156205,22067,4943,ME,OC
3658,3659,336512,ADITHYA S,29-08-2005,SC,78.50,156253,22088,3810,ME,SC
3659,3660,243612,SAKTHIVEL S,12-01-2004,BC,78.00,156268,22094,1421,CE,BC

In [ ]:
df_clean.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND*_2022.xlsx', index=False)

## üìä 2.3. Merge Excel Files Across Rounds
*Combining multiple rounds (R1-R4) into a single DataFrame.*

In [ ]:

# Step 1: Mount Google Drive
drive.mount('/content/drive')

# Step 2: Define paths to your Excel files in Drive
file1 = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND1_2022.xlsx'
file2 = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND2_2022.xlsx'
file3 = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND3_2022.xlsx'
file4 = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_ROUND4_2022.xlsx'

# Step 3: Read all Excel files into DataFrames
df1 = pd.read_excel(file1)
df2 = pd.read_excel(file2)
df3 = pd.read_excel(file3)
df4 = pd.read_excel(file4)

# Step 4: Merge all DataFrames using outer join on columns
merged_df = pd.concat([df1, df2, df3, df4], axis=0, join='outer', ignore_index=True)

# Step 5: Optional ‚Äì Save merged result back to Excel
merged_df.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_2022.xlsx', index=False)

print("Merged file saved to: merged_output.xlsx")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Merged file saved to: merged_output.xlsx

In [ ]:
merged_df

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,AGGR MARK,GENERAL RANK,COMMUNITY,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY,DOB
0,1,259423,JOTHI SRI S,198.0,744,MBC,4,1,CS,MBC,NaN
1,2,252228,DHARANI T,198.0,801,BC,5,2006,EC,OC,NaN
2,3,336834,CHANDRU G,198.0,952,BC,7,4,CS,BC,NaN
3,4,363584,VARSAA J V,197.5,996,BC,8,1,EE,OC,NaN
4,5,354912,DEVADHARSHINI K,197.5,1115,BC,12,1,IM,OC,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8595,3656,268654,CHANDHURU R M,80.0,156066,BC,22011,4946,CS,BC,12-07-2005
8596,3657,333602,S.dhanushraj,80.0,156111,BC,22025,3819,IC,OC,14-12-2004
8597,3658,402708,BALAMURUGAN G,79.5,156205,MBC,22067,4943,ME,OC,01-04-2005
8598,3659,336512,ADITHYA S,78.5,156253,SC,22088,3810,ME,SC,29-08-2005
8599,3660,243612,SAKTHIVEL S,78.0,156268,BC,22094,1421,CE,BC,12-01-2004

## üìâ 2.4. Rank Conversion & Sorting
*Converting rank strings to numeric and sorting accordingly.*

In [ ]:
merged_df['GOVT RANK'] = pd.to_numeric(merged_df['GOVT RANK'], errors='coerce')
merged_df.sort_values(by='GOVT RANK', ascending=True)

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,AGGR MARK,GENERAL RANK,COMMUNITY,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY,DOB
0,1,259423,JOTHI SRI S,198.000,744,MBC,4.0,1,CS,MBC,NaN
1,2,252228,DHARANI T,198.000,801,BC,5.0,2006,EC,OC,NaN
2,3,336834,CHANDRU G,198.000,952,BC,7.0,4,CS,BC,NaN
3,4,363584,VARSAA J V,197.500,996,BC,8.0,1,EE,OC,NaN
4,5,354912,DEVADHARSHINI K,197.500,1115,BC,12.0,1,IM,OC,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3793,2147,306704,Boominathan A,141.395,77806,MBC,NaN,5942,EE,OC,20-05-2004
3985,2339,371515,SAMURAJ M,139.120,80873,SCA,NaN,5862,AG,OC,27-08-2003
4036,2390,296873,ABISHEK S,138.985,81645,SC,NaN,3826,EE,SC,01-05-2004
4446,2800,377408,MANINIVASH R,134.535,87611A,MBC,NaN,2342,CE,OC,11-11-2002
4531,2885,270757,DHURUVA DHARSHANA P,134.000,88809,BC,NaN,3803,IT,OC,11-03-2005

In [ ]:
merged_df['ALLOTTED CATEGORY'].unique()

array(['MBC', 'OC', 'BC', 'SC', 'BCM', 'SCA', 'ST'], dtype=object)

# üßÆ 3. Data Transformation & Aggregation
*Objective: Summarize, restructure, and compute new representations*

## üß∞ 3.1. Template for CUTOFF & RANKLIST Table
*Creating the base structure for data aggregation.*

In [ ]:
# Define the column names
columns = [
    'COLLEGE CODE', 'BRANCH CODE', 'MBC', 'OC', 'BC', 'BCM',
    'SC', 'SCA', 'ST', 'MBCDNC', 'MBCV'
]

# Create the empty DataFrame
df = pd.DataFrame(columns=columns)

# Display the DataFrame
print(df)

Empty DataFrame
Columns: [COLLEGE CODE, BRANCH CODE, MBC, OC, BC, BCM, SC, SCA, ST, MBCDNC, MBCV]
Index: []

In [ ]:
df_2022 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_2022.xlsx')
df_2022

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,AGGR MARK,GENERAL RANK,COMMUNITY,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY,DOB
0,1,259423,JOTHI SRI S,198.0,744,MBC,4,1,CS,MBC,NaN
1,2,252228,DHARANI T,198.0,801,BC,5,2006,EC,OC,NaN
2,3,336834,CHANDRU G,198.0,952,BC,7,4,CS,BC,NaN
3,4,363584,VARSAA J V,197.5,996,BC,8,1,EE,OC,NaN
4,5,354912,DEVADHARSHINI K,197.5,1115,BC,12,1,IM,OC,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8595,3656,268654,CHANDHURU R M,80.0,156066,BC,22011,4946,CS,BC,12-07-2005
8596,3657,333602,S.dhanushraj,80.0,156111,BC,22025,3819,IC,OC,14-12-2004
8597,3658,402708,BALAMURUGAN G,79.5,156205,MBC,22067,4943,ME,OC,01-04-2005
8598,3659,336512,ADITHYA S,78.5,156253,SC,22088,3810,ME,SC,29-08-2005
8599,3660,243612,SAKTHIVEL S,78.0,156268,BC,22094,1421,CE,BC,12-01-2004

In [ ]:
df_2023 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2023.xlsx')
df_2023

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,COMMUNITY,AGGR MARK,GENERAL RANK,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY,DOB
0,1,311710,SARAVANAKUMAR B,BC,199.0,317,3,1,CM,OC,NaN
1,2,333573,MUTHUSANKAR A,BC,198.5,608,4A,1,EC,OC,NaN
2,3,320683,KAVITHA R,BC,198.5,731,6,1,EC,BC,NaN
3,4,257919,SANDHIYA S,BC,198.5,774,8,2006,CM,OC,NaN
4,5,259225,HARIRAJ V,MBC,198.0,826,9,1315,CJ,OC,NaN
...,...,...,...,...,...,...,...,...,...,...,...
10896,4830,276719,MOHAMED YASITH S,BCM,80.0,176678,27838,1319,CE,BCM,21-10-2005
10897,4831,287723,KARTHIKEYAN V,MBC,80.0,176695,27846,4934,EE,MBC,29-10-2005
10898,4832,268002,MOHANRAM K,MBC,80.0,176707,27853,4969,ME,MBC,24-06-2004
10899,4833,400080,GANESH M,MBC,80.0,176720,27860,4957,ME,MBC,26-12-2004
10900,4834,403817,PARTHIBAN P,SC,80.0,176728,27864,5904,ME,SC,20-03-2005

In [ ]:
df_2024 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2024.xlsx')
df_2024

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,DOB,COMMUNITY,AGGR MARK,GENERAL RANK,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY
0,1,343259,HARISH R,08-12-2006,MBC,200.0,30,1,1,CS,MBC
1,2,287746,RAVANI S,22-10-2006,BC,199.5,135,1A,1,EC,OC
2,3,401954,SARAVANAN M,05-12-2006,BC,198.5,431,3,1315,EC,OC
3,4,376589,MADHUSRI S,30-03-2007,MBC,198.5,480,4,1,CM,OC
4,5,231546,SUJITH T,08-10-2006,BC,198.5,484,5,1315,CS,BC
...,...,...,...,...,...,...,...,...,...,...,...
12752,4694,223101,Momeena,21-09-2006,SC,82.0,NaN,31597,1229,EE,SC
12753,4695,371977,SANTHOSH S,27-12-2007,SC,80.0,NaN,31752,4929,CE,SC
12754,4696,443778,SUBASH P,08-06-2005,SCA,80.0,NaN,31779,1123,MU,SCA
12755,4697,344788,JAYASRI J,18-03-2006,SC,79.5,NaN,31780,1523,AU,SC
12756,4698,326628,MOHAMED AKIL U,22-02-2007,BCM,79.0,NaN,31783,4934,ME,BCM

In [ ]:
import re
import numpy as np

def parse_rank(rank_str):
    """
    If already numeric, just return the int.
    """
    if pd.isna(rank_str):
        return np.nan
    match = re.match(r"^(\d+)([A-Z]+)$", str(rank_str).strip().upper())
    if match:
        number = int(match.group(1))
        return float(number)
    else:
        return float(rank_str)

## üìã 3.2. Create Cutoff Table
*Populating minimum aggregate marks by category.*

In [ ]:
# A temporary DataFrame for generate GOVT_ACADEMIC_202x_CUTOFF
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [COLLEGE CODE, BRANCH CODE, MBC, OC, BC, BCM, SC, SCA, ST, MBCDNC, MBCV]
Index: []

In [ ]:
for index, row in df_2022.iterrows():
    college_code = row['COLLEGE CODE']
    branch_code = row['BRANCH CODE']
    allot_category = row['ALLOTTED CATEGORY']
    aggr_mark = row['AGGR MARK']

    # Try to find existing row with same college and branch
    match_idx = df[
        (df['COLLEGE CODE'] == college_code) &
        (df['BRANCH CODE'] == branch_code)
    ].index

    if match_idx.empty:
        # No existing row ‚Äì add a new one
        new_row = {
            'COLLEGE CODE': college_code,
            'BRANCH CODE': branch_code,
            allot_category: aggr_mark
        }
        df.loc[len(df)] = new_row
    else:
        # Row exists ‚Äì update if this category is new or aggr_mark is lower
        idx = match_idx[0]
        current_val = df.at[idx, allot_category]
        if pd.isna(current_val) or aggr_mark < current_val:
            df.at[idx, allot_category] = aggr_mark

In [ ]:
df.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_2022_CUTOFF.xlsx', index=False)

## üìã 3.3. Create Ranklist Table
*Populating maximum rank by category.*

In [ ]:
# A temporary DataFrame for generate GOVT_ACADEMIC_202x_RANKLIST
df1 = pd.DataFrame(columns=columns)

In [ ]:
for index, row in df_2022.iterrows():
    college_code = row['COLLEGE CODE']
    branch_code = row['BRANCH CODE']
    allot_category = row['ALLOTTED CATEGORY']
    govt_rank = row['GOVT RANK']

    parsed_rank = parse_rank(govt_rank)

    match_idx = df1[
        (df1['COLLEGE CODE'] == college_code) &
        (df1['BRANCH CODE'] == branch_code)
    ].index

    if match_idx.empty:
        # Add new row with current rank
        new_row = {
            'COLLEGE CODE': college_code,
            'BRANCH CODE': branch_code,
            allot_category: parsed_rank
        }
        df1.loc[len(df1)] = new_row
    else:
        # Compare and update only if current rank is better (i.e. smaller)
        idx = match_idx[0]
        existing_val = df1.at[idx, allot_category]
        existing_rank = parse_rank(existing_val)
        if pd.isna(existing_rank) or parsed_rank > existing_rank:
            df1.at[idx, allot_category] = parsed_rank

## Some data exploration in the middle
*Intentionally left undeleted as this is how the story to be framed is churned out. (Could be ignored)*

In [ ]:
df1.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_2022_RANKLIST.xlsx', index=False)

In [ ]:
df2 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2022_RANKLIST.xlsx')

In [ ]:
# Check if df2 is a subset of df1
is_subset = df2.merge(df1, how='left', indicator=True)['_merge'].eq('both').all()

print("Is subset:", is_subset)

Is subset: False

In [ ]:
df_2022[
    (df_2022['COLLEGE CODE'] == 1) &
    (df_2022['ALLOTTED CATEGORY'] == 'MBC') &
    (df_2022['BRANCH CODE'] == 'ME')
    ]

,S NO,APPLN NUMBER,NAME OF THE CANDIDATE,AGGR MARK,GENERAL RANK,COMMUNITY,GOVT RANK,COLLEGE CODE,BRANCH CODE,ALLOTTED CATEGORY,DOB
72,73,340194,Dhanabal C,191.0,6656,MBC,109,1,ME,MBC,NaN
180,181,353326,ARAVIND V,186.5,12557,MBC,271,1,ME,MBC,NaN

In [ ]:
df1[(df1['COLLEGE CODE'] == 1)]

,COLLEGE CODE,BRANCH CODE,MBC,OC,BC,BCM,SC,SCA,ST,MBCDNC,MBCV
0,1,CS,4.0,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN
3,1,EE,148.0,8.0,54.0,NaN,255.0,NaN,NaN,NaN,NaN
4,1,IM,36.0,29.0,40.0,165.0,219.0,NaN,NaN,NaN,NaN
5,1,EC,13.0,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN
6,1,CM,24.0,22.0,30.0,45.0,99.0,NaN,NaN,NaN,NaN
8,1,GI,108.0,20.0,299.0,NaN,NaN,NaN,NaN,NaN,NaN
12,1,EM,83.0,37.0,41.0,NaN,246.0,915.0,NaN,NaN,NaN
28,1,ME,271.0,102.0,213.0,NaN,715.0,868.0,NaN,NaN,NaN
30,1,BY,279.0,NaN,101.0,NaN,499.0,NaN,NaN,NaN,NaN
44,1,CE,241.0,138.0,337.0,NaN,270.0,NaN,NaN,NaN,NaN
70,1,XC,NaN,234.0,454.0,NaN,NaN,NaN,NaN,NaN,NaN
74,1,MA,NaN,248.0,1006.0,NaN,NaN,NaN,NaN,NaN,NaN
87,1,IE,NaN,296.0,588.0,NaN,813.0,NaN,NaN,NaN,NaN
95,1,MN,531.0,321.0,381.0,NaN,1001.0,NaN,NaN,NaN,NaN
98,1,PT,NaN,329.0,537.0,NaN,NaN,NaN,6457.0,NaN,NaN
117,1,XM,400.0,390.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,1,MI,NaN,553.0,739.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[(df['COLLEGE CODE'] == 1)]

,COLLEGE CODE,BRANCH CODE,MBC,OC,BC,BCM,SC,SCA,ST,MBCDNC,MBCV
0,1,CS,200.0,NaN,197.5,NaN,NaN,NaN,NaN,NaN,NaN
1,1,EC,195.0,199.5,NaN,NaN,196.5,NaN,NaN,NaN,NaN
3,1,CM,196.5,196.5,196.0,NaN,192.5,NaN,181.5,NaN,NaN
6,1,CE,190.0,193.0,191.0,NaN,184.5,NaN,NaN,NaN,NaN
8,1,EM,194.5,197.5,195.5,NaN,190.5,NaN,NaN,NaN,NaN
12,1,IM,194.5,195.5,195.0,188.5,NaN,189.5,NaN,NaN,NaN
22,1,EE,193.0,194.5,193.0,NaN,190.0,NaN,NaN,NaN,NaN
41,1,ME,185.5,188.0,185.0,NaN,180.5,175.5,NaN,NaN,NaN
51,1,BY,190.5,191.5,191.0,NaN,176.5,NaN,NaN,NaN,NaN
55,1,EL,NaN,191.0,188.0,NaN,NaN,NaN,NaN,NaN,NaN
72,1,XC,NaN,190.0,189.0,NaN,NaN,NaN,NaN,NaN,NaN
97,1,MA,NaN,188.5,169.5,NaN,NaN,NaN,NaN,NaN,NaN
184,1,IE,184.0,185.0,183.5,NaN,176.5,NaN,NaN,NaN,NaN
188,1,GI,184.5,185.0,184.0,174.0,NaN,NaN,NaN,NaN,NaN
198,1,MI,NaN,184.5,184.5,NaN,NaN,NaN,NaN,NaN,NaN
200,1,XM,NaN,184.5,174.0,NaN,NaN,NaN,NaN,NaN,NaN
228,1,MN,182.0,184.0,173.0,168.0,176.5,NaN,NaN,NaN,NaN
387,1,PT,177.0,177.5,168.5,NaN,173.0,NaN,NaN,NaN,NaN

In [ ]:
df[(df['COLLEGE CODE'] == 1)].head(2).equals(df1[(df1['COLLEGE CODE'] == 1)].head(2))

False

## üßæ 3.4. Cutoff Aggregation (2022, 2023, 2024)
*Calculating average cutoff values over three years.*

In [ ]:
df_cutoff2022 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_2022_CUTOFF.xlsx')
df_cutoff2023 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2023_CUTOFF.xlsx')
df_cutoff2024 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2024_CUTOFF.xlsx')

In [ ]:
df_cutoff_avg = pd.DataFrame(columns=columns)

In [ ]:
college_codes = set()
branch_codes = set()

for index, row in df_cutoff2022.iterrows():
    college_code = row['COLLEGE CODE']
    college_codes.add(college_code)
    branch_code = row['BRANCH CODE']
    branch_codes.add(branch_code)

for index, row in df_cutoff2023.iterrows():
    college_code = row['COLLEGE CODE']
    college_codes.add(college_code)
    branch_code = row['BRANCH CODE']
    branch_codes.add(branch_code)

for index, row in df_cutoff2024.iterrows():
    college_code = row['COLLEGE CODE']
    college_codes.add(college_code)
    branch_code = row['BRANCH CODE']
    branch_codes.add(branch_code)

college_codes = list(college_codes)
branch_codes = list(branch_codes)

len(college_codes), len(branch_codes)

(451, 110)

In [ ]:
for college_code in college_codes:
    for branch_code in branch_codes:
        cutoff = [[] for _ in range(9)]
        for df in [df_cutoff2022, df_cutoff2023, df_cutoff2024]:
            try:
                list_of_marks = df[
                    (df['COLLEGE CODE'] == college_code) &
                    (df['BRANCH CODE'] == branch_code)
                ].iloc[0, 2:].tolist()
                for idx, mark in enumerate(list_of_marks):
                    cutoff[idx].append(mark)
            except:
                pass
        # calculate avg cutoff
        avg_cutoff = [0 for _ in range(9)]
        for idx, each_cat in enumerate(cutoff):
            each_cat_clean = [x for x in each_cat if str(x) != 'nan']
            avg_cutoff[idx] = sum(each_cat_clean) / len(each_cat_clean) if each_cat_clean else 0
        if avg_cutoff != [0]*9:
            df_cutoff_avg.loc[len(df_cutoff_avg)] = [college_code, branch_code] + avg_cutoff

df_cutoff_avg

,COLLEGE CODE,BRANCH CODE,MBC,OC,BC,BCM,SC,SCA,ST,MBCDNC,MBCV
0,1,IM,195.333333,196.166667,194.500000,189.0,188.750000,184.0,0.0,0,0
1,1,PT,177.000000,182.666667,170.991667,0.0,169.750000,0.0,136.5,0,0
2,1,XM,183.500000,184.000000,176.500000,0.0,0.000000,178.5,0.0,0,0
3,1,EM,193.000000,195.500000,195.250000,0.0,188.750000,175.5,0.0,0,0
4,1,EC,196.333333,199.000000,198.500000,0.0,193.833333,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3612,2025,EV,0.000000,176.000000,170.500000,0.0,0.000000,0.0,0.0,0,0
3613,2025,EE,167.000000,172.756667,154.833333,134.5,149.586667,151.0,0.0,0,0
3614,2025,AD,177.500000,182.833333,180.166667,0.0,173.000000,0.0,0.0,0,0
3615,2025,ME,160.000000,169.500000,144.666667,0.0,147.250000,130.5,0.0,0,0
3616,2025,CS,174.500000,184.000000,183.166667,0.0,173.000000,0.0,0.0,0,0

In [ ]:
df_cutoff_avg.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_CUTOFF_AVG.xlsx', index=False)

## üìà 3.5. Rank Aggregation (2022, 2023, 2024)
*Calculating average rank values over three years.*

In [ ]:
df_ranklist2022 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_2022_RANKLIST.xlsx')
df_ranklist2023 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2023_RANKLIST.xlsx')
df_ranklist2024 = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_2024_RANKLIST.xlsx')

In [ ]:
df_ranklist_avg = pd.DataFrame(columns=columns)

In [ ]:
for college_code in college_codes:
    for branch_code in branch_codes:
        ranklist = [[] for _ in range(9)]
        for df in [df_ranklist2022, df_ranklist2023, df_ranklist2024]:
            try:
                list_of_ranks = df[
                    (df['COLLEGE CODE'] == college_code) &
                    (df['BRANCH CODE'] == branch_code)
                ].iloc[0, 2:].tolist()
                for idx, rank in enumerate(list_of_ranks):
                    ranklist[idx].append(rank)
            except:
                pass
        # calculate avg rank
        avg_rank = [0 for _ in range(9)]
        for idx, each_rank in enumerate(ranklist):
            each_rank_clean = [x for x in each_rank if str(x) != 'nan']
            avg_rank[idx] = sum(each_rank_clean) / len(each_rank_clean) if each_rank_clean else 0
        if avg_rank != [0]*9:
            df_ranklist_avg.loc[len(df_ranklist_avg)] = [college_code, branch_code] + avg_rank

df_ranklist_avg

,COLLEGE CODE,BRANCH CODE,MBC,OC,BC,BCM,SC,SCA,ST,MBCDNC,MBCV
0,1,IM,49.000000,33.666667,60.000000,246.0,210.500000,578.5,0.0,0,0
1,1,PT,1319.500000,747.666667,2179.000000,0.0,2325.000000,0.0,6457.0,0,0
2,1,XM,400.000000,526.500000,1440.000000,0.0,0.000000,894.0,0.0,0,0
3,1,EM,96.666667,46.666667,38.500000,0.0,223.500000,915.0,0.0,0,0
4,1,EC,32.666667,2.500000,6.000000,0.0,74.666667,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3612,2025,EV,0.000000,1777.000000,2720.000000,0.0,0.000000,0.0,0.0,0,0
3613,2025,EE,2849.000000,1592.000000,4553.000000,11322.0,6752.333333,4109.0,0.0,0,0
3614,2025,AD,1070.500000,577.666667,812.666667,0.0,1585.500000,0.0,0.0,0,0
3615,2025,ME,3481.000000,2129.666667,6791.000000,0.0,5858.000000,12942.0,0.0,0,0
3616,2025,CS,1325.000000,550.500000,701.666667,0.0,1553.666667,0.0,0.0,0,0

In [ ]:
df_ranklist_avg.to_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/GOVT_ACADEMIC_RANKLIST_AVG.xlsx', index=False)

## üìë 3.6. Consolidated Excel Export (8 sheets)
*Writing all relevant data to a single Excel workbook.*

In [ ]:
with pd.ExcelWriter("/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx", engine='xlsxwriter') as writer:
    df_cutoff2022.to_excel(writer, sheet_name="Cutoff_2022", index=False)
    df_cutoff2023.to_excel(writer, sheet_name="Cutoff_2023", index=False)
    df_cutoff2024.to_excel(writer, sheet_name="Cutoff_2024", index=False)
    df_ranklist2022.to_excel(writer, sheet_name="Ranklist_2022", index=False)
    df_ranklist2023.to_excel(writer, sheet_name="Ranklist_2023", index=False)
    df_ranklist2024.to_excel(writer, sheet_name="Ranklist_2024", index=False)
    df_cutoff_avg.to_excel(writer, sheet_name="Avg_Cutoff", index=False)
    df_ranklist_avg.to_excel(writer, sheet_name="Avg_Rank", index=False)

In [ ]:
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading XlsxWriter-3.2.3-py3-none-any.whl.metadata (2.7 kB)
Downloading XlsxWriter-3.2.3-py3-none-any.whl (169 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 169.4/169.4 kB 2.6 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.3

## üî† 3.7. Code-to-Name Mapping (College & Branch)
*Creating mapping dictionaries.*

In [ ]:
df_final = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx')
df_code_clg = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/TNEA_2024_Code_to_colleges.xlsx', sheet_name='Table 1')
df_code_branch = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/TNEA_2024_Code_to_colleges.xlsx', sheet_name='Table 2')

In [ ]:
df_code_clg.head()

,S.No.,TNEA\nCode No.,Name of the College,Page No.
0,1,1441,A K T Memorial College of Engineering and Tech...,120
1,2,1436,"A R Engineering College, Vadakuchipalayam, Kap...",117
2,3,3821,"A R J College of Engineering and Technology, M...",332
3,4,1232,"A R M College of Engineering and Technology, S...",62
4,5,3801,"A V C College of Engineering, Mannampandal Pos...",316

In [ ]:
df_code_branch.head()

   SL.NO BRANCH                                               NAME
0      1     AD           ARTIFICIAL INTELLIGENCE AND DATA SCIENCE
1      2     AE                           AERONAUTICAL ENGINEERING
2      3     AG                           AGRICULTURAL ENGINEERING
3      4     AL       ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING
4      5     AM  COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...

In [ ]:
code_clg = df_code_clg.set_index('TNEA\nCode No.')['Name of the College'].to_dict()
code_branch = df_code_branch.set_index('BRANCH')['NAME'].to_dict()

In [ ]:
# Mapping dictionary
college_name_map = {
    2314: 'Muthayammal College of Engineering, Kakkaveri Post, Namakkal District 637408',
    2328: 'K S R Institute for Engineering and Technology (Autonomous) Thokkavadi Namakkal District 637215',
    2378: 'Cherraan College of Technology, Cheran Nagar, Thittuparai, Kangeyam,  Tiruppur, Tamil Nadu ‚Äì 638 701.',
    2606: 'Jayam College of Engineering and Technology, Nallanur Post, Dharmapuri District 636813',
    2661: 'Vivekanandha College of Technology for Women, Sathinaickenpalayam, Elayampalayam Village, Kumaramangalam, Namakkal District 637205',
    2665: 'Mahendra Institute of Engineering and Technology, Mahendrapuri, Mallasamudram, Namakkal District 637503',
    4972: 'AMRITA College of Engineering and Technology, Erachakulam Post, Kanyakumari District 629902',
    1313: 'Shree Motilal Kanhaiyalal (SMK)Fomra Institute of Technology, Old Mahabalipuram Road (OMR), Kelambakkam, Chengalpattu District 603103',
    1334: 'ARS College of Engineering, Maraimalai Nagar Post, Chengalpattu District 603209',
    3403: 'Mahalakshmi Engineering College, Trichy-Salem Highways, (Near No.1 Tollgate), Melpathu, Siruganbur Post, Tiruchirappalli District 621213',
    1398: 'Chennai Institute of Technology and Applied Research, Sarathy Nagar, Puduppair, Kundrathur, Chennnai ‚Äì 600 069.',
    3462: 'Ariyalur Engineering College, NH-227, Trichy-Chithambaram NH, Karuppur-Senapathy Post, Ariyalur District 621707',
    1533: 'Panimalar Institute Of Technology',
    3802: 'Shri Angalamman College of Engineering and Technology, Siruganoor, Tiruchirapalli-621 105',
    3809: 'Kurinji College of Engineering and Technology, Manapparai, Tiruchirappalli District 621307',
    3859: 'Sembodai Rukmani Varatharajan Engineering College, Sembodai Village, Vedaraniam, Nagappattinam District 614820',
    2355: 'Cheran College of Engineering, Cheran Nagar, Karur-Coimbatore NH-67, Aravakurichi Taluk, K.Paramathi Village, Karur District-639111',
    4948: 'Rajas Institute of Technology, Ozhuginasery, Kanyakumari District, Nagercoil-629001',
    1205: 'Lord Venkateshwara Engineering College, Puliyambakkam, Walajabad taluk, Kanchipuram -631605'
}

In [ ]:
# add college_name_map to code_clg
code_clg.update(college_name_map)
code_clg

{1441: 'A K T Memorial College of Engineering and Technology, Neelamangalam Village, Kallakurichi District 606202',
 1436: 'A R Engineering College, Vadakuchipalayam, Kappiyampuliyur Post, Villupuram District 605601',
 3821: 'A R J College of Engineering and Technology, Mannargudi Taluk, Thiruvarur District 614001',
 1232: 'A R M College of Engineering and Technology, Sattamangalam, Maraimalainagar, Chengalpattu District 603209',
 3801: 'A V C College of Engineering, Mannampandal Post, MayiladuthuraiDistrict 609305',
 2636: 'A V S Engineering College, Military Road, Ammapet, Salem District 636003',
 4937: 'A.R College of Engineering and Technology, A.R Nagar, Kadayam-Alangulam Road, Therkkumadathoor P.o,Ambasamudram Taluk,Tirunelveli-627423',
 4680: 'AAA College of Engineering and Technology, Kamarajar Educational Road, Amathur Village, Sivakasi, Virudhunagar District 626005',
 1135: 'Aalim Muhammed Salegh Academy of Architecture, Muthapudupet, Avadi IAF, Chennai 600055',
 1101: 'Aalim Muhammed Salegh College of Engineering, Muthapudupet, Avadi IAF, Chennai 600055',
 1233: 'Adhi College of Engineering and Technology, Pazhayaseevaram, Madura Sankarapuram Village, Kancheepuram District 631605',
 1501: 'Adhiparasakthi College of Engineering, Kalavai, Ranipet District 632506',
 1401: 'Adhiparasakthi Engineering College, Melmaruvathur, Chengalpattu District 603319',
 2601: 'Adhiyamaan  College of Engineering (Autonomous), Hosur, Krishnagiri District 635109',
 2744: 'Adithya Institute of Technology, Kurumbapalayam Village, Coimbatore District 641107',
 1316: 'Agni College of Technology (Autonomous), Old Mahabalipuram Road (OMR), Thalambur Village, Chengalpattu District 603103',
 5544: 'Agni School of Architecture and Design Excellence (ASADE),NH45,Trichy Road,Morepatty (Post),Vadamadurai (Via),Dindigul District 624 802',
 2332: 'Aishwarya College of Engineering and Technology, Errattaikaradu Paruvachi Post, Anthiyur (Via), Bhavani Taluk, Erode District 638312',
 2763: 'Akshaya College of Engineering and Technology, Kinathukadavu, Coimbatore District 642109',
 5901: 'Alagappa Chettair Government College of Engineering and Technology (Autonomous), Karaikudi, Sivagangai District 630004',
 2652: 'AL-Ameen Engineering College (Autonomous), Karundevan Palayam, Nanjai Uthukuli Post, Erode District 638104',
 1228: 'Alpha College of Engineering, No.34, Udayavar Koil Street, Poonamallee, Thirumazhisai, Chennai - 600124',
 1303: 'Anand Institute of Higher Technology, Old Mahabalipuram Road (OMR), Kazhipattur, Chengalpattu District  603103',
 2733: 'Angel College of Engineering and Technology, P.K.Palayam, Ugayanur Village, Tirupur District 641 665',
 3803: 'Anjalai Ammal Mahalingam Engineering College, Kovilvenni, Thiruvarur District 614403',
 2025: 'Anna University Regional Campus - Coimbatore, Maruthamalai Main Road, Navavoor Bharathiyar University Post, Somayampalayam, Coimbatore District 641046',
 5010: 'Anna University Regional Campus - Madurai, Kanyakumari National Highway, Keelakuilkudi, Madurai District 625019',
 4020: 'Anna University Regional Campus - Tirunelveli, Trivandrum Road, Palayamkottai, Tirunelveli District 627007',
 3849: 'Annai College of Engineering and Technology, Anakudi Road, Kovilacheri, Kumbakonam, Thanjavur District 612503',
 2602: 'Annai Mathammal Sheela Engineering College, Erumapatty Post, Namakkal District 637013',
 1137: 'Annai Mira College of Engineering and Technology, Arcot Road, Arappakkam Village, Walaja Taulk, Ranipet District 632 517',
 1402: 'Annai Teresa College of Engineering, Thirunavalur, Kallakkurichi District 607204',
 4999: 'Annai Vailankanni College of Engineering, Pothaiyadi Salai, Pottalkulam, Azhagappapuram, Kanyakumari District 629401',
 1133: 'Annai Veilankannis College of Engineering, Gandhi Road, Nedungundram, Chennai 600048',
 5: 'Annamalai University Faculty of Engineering and Technology,Annamalai nagar,Cuddalore',
 1524: 'Annamalaiar College of Engineering, Modaiyur Village, Polur Taluk, Thiruvannamalai District 606902',
 2648: 'Annapoorana Engineering College (Autonomous), Sankari Main Road, NH-47, Periaseeragapadi, Salem District 636308',
 1230: 'Apollo Engineering College, Mevaloorkuppam, Valarpuram Post, Sriperumpudur, Kancheepuram District 602105',
 3804: 'Arasu Engineering  College, Chennai Main Road, Kumbakonam, Thanjavur District 612501',
 3461: 'Arifa Institute of Technology(Formly Haji sheik Ismail Engineering College), Esanoor, Keelaiyur Post, Thirukkuvalai Taluk, Nagapattinam District 611103',
 2367: 'Arjun College of Technology, Chettiyakkapalayam, Kinathukadavu, Coimbatore District 642120',
 4679: 'Arul Tharum VPMM College of Architecture V.P.M.NAGAR, KRISHNANKOIL 626190',
 4979: 'Arul Tharum VPMM College of Engineering and Technology (Formerly V.P.Muthaiah Pillai Meenakshi Ammal Engineering College for Women), Krishnakoil,Virudhunagar-626 190',
 1503: 'Arulmigu  Meenakshi Amman College of Engineering, Vadamavandal,Thiruvannamalai District 604410',
 2356: 'Arulmurugan College of Engineering, Karvazhi Road, Thennilai Post, Karur District 639206',
 4944: 'Arunachala College of Engineering for Women, Thanka Gardens, Manavilai, Vellichanthai, Nagercoil, Kanyakumari District 629203',
 1504: 'Arunai Engineering College, Mathur, Thiruvannamalai District 606603',
 1423: 'Asan Memorial College of Engineering and Technology,Chengalpattu-603 001.',
 2338: 'Asian College of Engineering and Technology, Asian College Road, Kondayampalayam, Near Saravanampatti, Coimbatore District 641110',
 3855: 'As-Salam College of Engineering and Technology, Thirumangalakudi, Aduthurai, Thiruvidaimaruthur, Thanjavur District 612102',
 2347: 'AVS College of Technology, Attur Main Road, Near AVS College of Arts & Science, Chinnagoundapuram, Salem District 636106',
 2702: 'Bannari Amman Institute of Technology (Autonomous), Sathyamanagalam, Erode District  638401',
 4992: 'Bethlahem Institute of Engineering, Karungal, Kanyakumari District 629157',
 1102: 'Bhajarang Engineering College NEAR AVADI, AYATHUR VILLAGE, VEPPAMPATTU (RS) THIRUVALLUR TALUK AND DISTRICT TAMILNADU 602024',
 5902: 'Bharath Niketan Engineering College, Thimmarasanaickanoor, Aundipatti, Theni District 625536',
 1519: 'Bharathidasan Engineering College, Nattrampalli Post, Thiruppathur District 635854',
 2643: 'Bharathiyar Institute of Engineering for Women, Deviayakurichi, Attur Taluk, Salem District 636112',
 2656: 'Builders Engineering college, Nathakadaiyur, Erode Road, Palayakottai Village, Kangeyam, Tiruppur District 638108',
 1505: 'C Abdul Hakeem College of Engineering and Technology, Melvisharam, Ranipet District 632509',
 3425: 'C K College of Engineering and Technology, Chellangkuppam, Cuddalore District 607003',
 2772: 'C M S College of Engineering and Technology, Appachigoundenpathy, Kumittipathi Post, Coimbatore District 641032',
 4952: 'C S I Institute of Technology, Thovalai, Kanyakumari District 629302',
 3784: 'C.A.R.E School of Architecture, No.27, Thayanur Village, Kuttapatti, Srirangam Taluk, Tiruchirappalli District 620009',
 1152: 'CAAD-Chennai Academy of Architecture and Design, No.516-2, Kannigaiper, Chennai-Thirupathi Highway, Near Periyapalayam Amman Temple, Chennai 601102',
 4953: 'CAPE Institute of Technology, Levingipuram, Tirunelveli District 627114',
 3841: 'CARE College of Engineering (Formerly C.A.R.E Group of Institutions), Thayanoor Village, Thayanoor Village, Kuttappatti, Srirangam Taluk, Tiruchirappalli District 620009',
 5012: 'Central Electrochemical Research Institute CECRI), Karaikudi, Sivagangai District 630006',
 1321: 'Central Institute of Petrochemicals Engineering and Technology (Formerly Central Institute of Plastics Engineering and Technology) (CIPET), Guindy, Chennai 600032',
 3926: 'Chendhuran College of Engineering and Technology, Madurai Road, Lenavilakku, Pilivalam Post, Pudukkottai - 622 507',
 1399: 'Chennai Institute of Technology, Puduper Village, Nandambakkam Post, Kundrathur, Chennai 600069',
 2630: 'Chettinad College of Engineering and Technology, NH-67, Trichy Main Road, Puliyur C F, Karur District 639114',
 2650: 'Christ The King Engineering College, Cecilia Gardens, Chikkarampalayam Village, Coimbatore District 641104',
 5703: 'Christian College of Engineering and Technology, Oddanchatram, Dindigul District 624619',
 2635: 'CMS College of Engineering, Emapuram Post, Namakkal District 637003',
 2704: 'Coimbatore Institute of Engineering and Technolgoy (Autonomous), Narasipuram Post, Coimbatore District 641109',
 2007: 'Coimbatore Institute of Technology (Autonomous), Civil Aerodrome Post, Coimbatore District 641014',
 2705: 'CSI College of Engineering, Ketti, The Nilgiris 643215',
 1202: 'D M I College of Engineering, Palanchoor, Nazrethpet, Chennai 602103',
 4946: 'D M I Engineering College, Aralvaimozhi Village, Thovalai, Kanyakumari District 629301',
 1138: 'Da Vinci School of Design and Architecture, Rajiv Gandhi Salai, Karapakkam, Chennai, Chengalpattu District 600097',
 1424: 'Dhaanish Ahmed College of Engineering, Padappai, Chennai 601301',
 2349: 'Dhaanish Ahmed Institute of Technology, Pichanur Post, (Near K G Chavadi), Coimbatore District 641105',
 1405: 'Dhanalakshmi College of  Engineering, Manimangalam, Chennai 601301',
 3805: 'Dhanalakshmi Srinivasan  Engineering College (Autonomous), Thuraiyur Road, Perambalur District 621212',
 2743: 'Dhanalakshmi Srinivasan College of Engineering (CBE), NH47, Palakkad Main Road, Navakkarai Post, Near Nandhi Temple, Coimbatore District 641105',
 1322: 'Dhanalakshmi Srinivasan College of Engineering and Technology, East Coast Road, Poonjeri, Chennai 603104',
 2345: 'Dhirajlal Gandhi College of Technology, Sikkanampatty, (Opp. to Airport), Omalur Taluk, Salem District 636309',
 4975: 'Dr. G U Pope College of Engineering, Sawyerpuram, Thoothukudi District 628251',
 2706: 'Dr. Mahalingam College of  Engineering and Technology (Autonomous), Mackinaickenpatti Post, Pollachi Taluk, Coimbatore District 642003',
 2736: 'Dr. N G P Institute of Technology (Autonomous), Kalapatti Road, Coimbatore District 641035',
 4954: 'Dr. Sivanthi Aditanar College of Engineering, Tiruchendur, Thoothukudi District 628215',
 3822: 'Dr.Navalar Nedunchezhiyan College of Engineering,Raja Nagar,Vaithiyanathapuram,tholudur, Cuddalore-606303',
 3806: 'E G S Pillay  Engineering College (Autonomous), Nagapattinam District 611002',
 1428: 'E. S. College of Engineering and Technology, Chennai Trunk Road, Ayyankoilpattu, Villupuram District 605602',
 2749: 'Easa College of Engineering and Technology, NH-47, Coimbatore-Palakkad Main Road, Navakarai Post, Coimbatore District 641105',
 1304: 'Easwari Engineering College (Autonomous), Ramapuram, Chennai 600089',
 4980: 'Einstein College of Engineering, Seethaparpanallur, Tirunelveli District 627012',
 2621: 'Er. Perumal Manimekalai College of Engineering, Near Koneripalli, Hosur, Krishnagiri District 635117',
 2707: 'Erode Sengunthar Engineering College (Autonomous), Thudupathi Post, Erode District 638057',
 2667: 'Excel College of Architecture and Planning, NH-544, Salem Main Road, Pallakapalayam, Sankari West Post, Komarapalayam Taluk, Namakkal District 637303',
 2634: 'Excel Engineering College (Autonomous), NH-544, Salem Main Road, Pallakapalayam, Sankari West Post, Komarapalayam Taluk, Namakkal District - 637303',
 5935: 'Fatima Michael College of Engineering and Technology, Sengottai Village, Sivagangai Main Road, Madurai District 625020',
 4955: 'Francis Xavier Engineering College (Autonomous), Vannarpettai, Tirunelveli District 627003',
 1407: 'G K M College of  Engineering and Technology, Alappakkam-Mappedu Road, Chennai 600063',
 1238: 'G R T Institute of Engineering and Technology, GRT Mahalakshmi Nagar, Chennai-Tirupathi Highway, Tiruttani Taluk, Thiruvallur District 631209',
 1507: 'Ganadipathy Tulsis Jain Engineering College, Kaniyambadi, Vellore District 632102',
 5924: 'Ganapathy Chettiar College of Engineering and Technology, Melakavanur Post, Paramakudi, Ramanathapuram District 623706',
 2341: 'Ganesh College of Engineering, Attur Main Road, Mettupatti, Salem District 636111',
 1523: 'Global Institute of Engineering and Technology, Bangalore-Chennai Highway, Melvisharam, Walajah Taluk, Ranipet District 632506',
 2624: 'Gnanamani College of Technology (Autonomous), Pachal Post, Namakkal District 637018',
 1123: 'Gojan School of Business and Technology, Alamathi, Chennai 600062',
 4686: 'Good Shepherd College of Engineering and Technology, Maruthamparai, Kanyakumari District 629101',
 2603: 'Government College of Engineering (Autonomous), Bargur, Krishnagiri District 635104',
 2615: 'Government College of Engineering (Autonomous), Karuppur, Salem District 636011',
 2709: 'Government College of Engineering (Formerly Institute of Road and Transport Technology), Vasavi College Post, Erode District 638316',
 2369: 'Government College of Engineering, Chettikkarai Post, Dharmapuri District 635704',
 3464: 'Government College of Engineering, Gandarvakottai Road, Sengipatti, Thanjavur District 613402',
 5009: 'Government College of Engineering, Melachokkanathapuram, Bodinayakkanur, Theni District 625582',
 3465: 'Government College of Engineering, Srirangam, Sethurappatti, Tiruchirappalli District 620012',
 4974: 'Government College of Engineering, Tirunelveli District 627007',
 2005: 'Government College of Technology (Autonomous), Thadagam Road, Coimbatore District 641013',
 4931: 'Grace College of Engineering, Chandy Nagar, Mullakkadu, Thoothukudi District 628005',
 2708: 'Hindusthan College of Engineering and Technology (Autonomous), Othakkalmandapam Post, Coimbatore District 641032',
 2740: 'Hindusthan Institute of Technology (Autonomous), Othakkalmandapam, Coimbatore District 641032',
 2373: 'Hindusthan School of Architecture, Othakkalmandabam Post, Coimbatore District 641032',
 4934: 'Holy Cross Engineering College, Vagaikulam, Sri Mulakarai, Srivaikuntam, Thoothukudi District 628851',
 1408: 'I F E T College of Engineering  (Autonomous), Gangarampalayam, Villupuram District 605108',
 1605: 'Idhaya Engineering College for Women, Chinnasalem, Kallakkurichi District 606201',
 3845: 'Imayam College of Engineering, Kannanur, Thuraiyur, Tiruchirappalli District 621206',
 4932: 'Immanuel Arasar J.J. College of Engineering, Edavilagam, Nattalam, Marthandam, Kanyakumari-629165',
 2343: 'Indian Institute of Handloom Technology, Foulke s Compound, Thillai Nagar, Salem District 636001',
 1229: 'Indira Institute of Engineering and Technology, VGR Gardens, Pandur, Thiruvallur District 631203',
 3831: 'Indra Ganesan College of Engineering, Madurai Main Road, Manikandam, Tiruchirappalli District 620012',
 4976: 'Infant Jesus College of Engineering, Thoothukudi Highway (NH7/A), Thoothukudi District 628851',
 2732: 'Info Institute of Engineering, Sarkar Samakulam, Coimbatore District 641107',
 2769: 'J C T College of Engineering and Technology, Pichanur, Coimbatore District 641105',
 3807: 'J J College of Engineering and Technology, Poolankulathupatti Post, Thiruchirappalli District 620009',
 2758: 'J K K Munirajah College of Technology, T N Palayam, Gobi Taluk, Erode District 638506',
 2647: 'J K K Nataraja College of Engineering and Technology, Komarapalayam Amani, Thattankuttai Panchayat, Namakkal District 638183',
 1126: 'J N N Institute of Engineering, Ushaa Garden, Kannigaipair Village, Uthukottai Taluk, Thiruvallur District 601102',
 4994: 'J P College of Engineering, College Road, Ayakudy, Tenkasi Taluk, Tenkasi District 627852',
 2651: 'Jai Shriram Engineering College, Dharapuram Road, Avinashi Palayam, Tiruppur District 638660',
 5537: 'Jainee College of Engineering and Technology, Dindigul-Theni Main Road (Near Vakkampatti), Dindigul District 624303',
 2350: 'Jairupaa College of Engineering, Thottiapalayam, Kathankanni Post, Kangayam, Tiruppur District 641 604',
 2762: 'Jansons Institute of Technology, Karumathampatty, Somaur, Coimbatore District 641659',
 1221: 'Jaya College of Engineering and Technology, Parivakkam, Poonamallee, Chennai 600056',
 1106: 'Jaya Engineering College, Thirunindravur, Chennai 602024',
 1107: 'Jaya Institute of Technology, Kanchipadi Post, Thiruvallur-Tiruttani NH  Road, Thiruvallur District 631204',
 1416: 'Jaya Sakthi Engineering College, Thirunindravur, Chennai 602024',
 1129: 'Jaya School of Architecture, Poonamallee By-Pass Road, Poonamallee, Chennai 600 056',
 2640: 'Jayalakshmi Institute of Technology, Thoppur, Dharmapuri District 635352',
 4956: 'Jayamatha Engineering College, Aralvaimozhi, Kanyakumari District - 629301',
 4957: 'Jayaraj Annapackiam CSI College of Engineering, Nazareth, Thoothukudi District 628617',
 3808: 'Jayaram College of Engineering and Technology, Karattampatti, Pagalavadi Po,Thuraivur, Trichy-621014',
 1235: 'Jei Mathaajee College of Engineering, Vishaandikuppam,Karappettai (via), Siruvakkam, Kancheepuram District 631 552',
 1306: 'Jeppiaar Engineering College, Old Mahabalipuram Road (OMR), Chennai 600119',
 1140: 'Jeppiaar Institute of Technology,kunnam Village,Sriperumpudur Taulk,Kancheepuram District 631604',
 1307: 'Jerusalem College of Engineering (Autonomous), Narayanapuram, Pallikaranai, Chennai 600 100',
 1311: 'K C G College of Technology(Autonomous), Karappakkam, Chennai 600096',
 5904: 'K L N College of Engineering (Autonomous), Pottapalayam, Sivagangai District 630611',
 2764: 'K P R Institute of Engineering and Technology (Autonomous), Kollupalayam Village, Arasur Panchayat, Coimbatore District 641407',
 3830: 'K Ramakrishnan College of Engineering (Autonomous), Kariyamanickam Road, Samayapuram, Manachanallur Taluk, Tiruchirappalli District 621112',
 3701: 'K Ramakrishnan College of Technology (Autonomous), Kariyamanickam Road, Samayapuram, Manachanallur Taluk, Tiruchirappalli District 621112',
 3456: 'K S K College of Engineering and Technology, Thanjavur Main Road, Darasuram, Kumbakonam, Thanjavur District 612702',
 2613: 'K S R College of Engineering (Autonomous), Tiruchengode, Namakkal District 637215',
 2607: 'K S Rangasamy College of Technology (Autonomous), Tiruchengode, Namakkal District 637215',
 4959: 'Kamaraj College of Engineering and Technology (Autonomous), Virudhunagar District 626001',
 5533: 'Karaikudi Institute of Technology and Karaikudi Institute of Management, KIT & KIM Technical Campus, Keeranipatti, Thalakkuvur, Karaikudi, Sivagangai District 630307',
 1409: 'Karpaga Vinayaga College of Engineering and Technology, Palayanoor Post, Maduranthagam Taluk, Chengalpattu District 603308',
 2710: 'Karpagam College of Engineering (Autonomous), Othakkalmandapam, Coimbatore District 641032',
 2735: 'Karpagam Institute of Technology, Seerapalayam Village, L&T By pass Road, Coimbatore District 641021',
 2745: 'Kathir College of Engineering, Neelambur, Avinashi Road, Coimbatore District',
 2751: 'KGISL Institute of Technology, KGISL Campus, Thudiyalur Road, Saravanampatti, Coimbatore District 641035',
 3905: 'Kings College of Engineering, Punalkulam, Pudukkottai District 613303',
 1207: 'Kings Engineering College, Sriperumpudur Taluk, Kancheepuram District 602105',
 1520: 'Kingston Engineering College, Chithoor Main Road, Christianpet Village, Katpadi Taluk,  Vellore District 632059',
 2750: 'KIT - Kalaignar Karunanidhi Institute of Technology (Autonomous), Kannampalayam, Coimbatore District 641402',
 2653: 'Knowledge Institute of Technology, KIOT Campus, Kakapalayam Post, Salem District 637504',
 2711: 'Kongu Engineering College (Autonomous), Perundurai, Erode District 638052',
 2344: 'Kongu School of Architecture, Kongu Engineering College Campus,Perundurai Railway Station Road, Thoppupalayam (Post), Perundurai,Erode District 638052',
 3826: 'Kongunadu College of Engineering and Technology (Autonomous), Tholurpatti, Thottiyam, Tiruchirappalli District 621215',
 3410: 'Krishnasamy College of Engineering and Technology, S Kumarapuram, Cuddalore District 607109',

In [ ]:
code_branch

{'AD': 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE',
 'AE': 'AERONAUTICAL ENGINEERING',
 'AG': 'AGRICULTURAL ENGINEERING',
 'AL': 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING',
 'AM': 'COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)',
 'AO': 'AEROSPACE ENGINEERING',
 'AP': 'APPAREL TECHNOLOGY (SS)',
 'AS': 'AUTOMOBILE ENGINEERING (SS)',
 'AT': 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)',
 'AU': 'AUTOMOBILE ENGINEERING',
 'BC': 'BIO TECHNOLOGY AND BIO CHEMICAL ENGINEERING',
 'BM': 'BIO MEDICAL ENGINEERING',
 'BP': 'B.PLAN',
 'BS': 'BIO TECHNOLOGY (SS)',
 'BT': 'BIO TECHNOLOGY',
 'BY': 'BIO MEDICAL ENGINEERING  (SS)',
 'CB': 'COMPUTER SCIENCE AND BUSSINESS SYSTEM',
 'CC': 'CHEMICAL AND ELECTRO CHEMICAL  ENGINEERING (SS)',
 'CD': 'COMPUTER SCIENCE AND DESIGN',
 'CE': 'CIVIL  ENGINEERING',
 'CF': 'COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)',
 'CG': 'COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING) (SS)',
 'CH': 'CHEMICAL  ENGINEERING',
 'CI': 'COMPUTER SCIENCE AND ENGINEERING (INTERNET OF THINGS)',
 'CJ': 'M.TECH. COMPUTER SCIENCE AND ENGINEERING (INTEGRATED 5\nYEARS)',
 'CL': 'CHEMICAL  ENGINEERING (SS)',
 'CM': 'COMPUTER SCIENCE AND ENGINEERING (SS)',
 'CN': 'CIVIL  ENGINEERING (SS)',
 'CO': 'COMPUTER AND  COMMUNICATION ENGINEERING',
 'CR': 'CERAMIC TECHNOLOGY (SS)',
 'CS': 'COMPUTER SCIENCE AND ENGINEERING',
 'CT': 'COMPUTER TECHNOLOGY',
 'CW': 'COMPUTER SCIENCE AND BUSINESS SYSTEM (SS)',
 'CY': 'CYBER SECURITY',
 'CZ': 'CIVIL AND STRUCTUTURAL ENGINEERING',
 'EC': 'ELECTRONICS AND COMMUNICATION ENGINEERING',
 'EE': 'ELECTRICAL AND ELECTRONICS ENGINEERING',
 'EI': 'ELECTRONICS AND INSTRUMENTATION ENGINEERING',
 'EM': 'ELECTRONICS AND COMMUNICATION ENGINEERING (SS)',
 'EN': 'ENVIRONMENTAL ENGINEERING',
 'ES': 'ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)',
 'ET': 'ELECTRONICS AND  TELECOMMUNICATION ENGINEERING',
 'EY': 'ELECTRICAL AND ELECTRONICS ENGINEERING (SS)',
 'FD': 'FOOD TECHNOLOGY',
 'FS': 'FOOD TECHNOLOGY (SS)',
 'FT': 'FASHION TECHNOLOGY',
 'FY': 'FASHION TECHNOLOGY (SS)',
 'GI': 'GEO INFORMATICS',
 'HT': 'HANDLOOM AND TEXTILE TECHNOLOGY',
 'IB': 'INDUSTRIAL BIO TECHNOLOGY',
 'IC': 'INSTRUMENTATION AND CONTROL ENGINEERING',
 'IE': 'INDUSTRIAL ENGINEERING',
 'IM': 'INFORMATION TECHNOLOGY (SS)',
 'IN': 'INDUSTRIAL ENGINEERING AND MANAGEMENT',
 'IS': 'INDUSTRIAL BIO TECHNOLOGY (SS)',
 'IT': 'INFORMATION TECHNOLOGY',
 'IY': 'INSTRUMENTATION AND CONTROL ENGINEERING (SS)',
 'LE': 'LEATHER TECHNOLOGY',
 'MA': 'MATERIAL SCIENCE AND ENGINEERING (SS)',
 'MC': 'MECHATRONICS',
 'MD': 'MEDICAL ELECTRONICS ENGINEERING',
 'ME': 'MECHANICAL ENGINEERING',
 'MF': 'MECHANICAL ENGINEERING (SS)',
 'MG': 'MECHATRONICS (SS)',
 'MH': 'MECHANICAL ENGINEERING (SANDWICH)',
 'MI': 'MINING ENGINEERING',
 'MM': 'MECHANICAL ENGINEERING (MANUFACTURING)',
 'MN': 'MANUFACTURING ENGINEERING',
 'MO': 'MECHANICAL AND MECHATRONICS ENGINEERING (ADDITIVE\nMANUFACTURING)',
 'MR': 'MARINE ENGINEERING',
 'MS': 'MECHANICAL ENGINEERING (SANDWICH) (SS)',
 'MT': 'METALLURGICAL ENGINEERING',
 'MU': 'MECHANICAL AND AUTOMATION ENGINEERING',
 'MY': 'METALLURGICAL ENGINEERING (SS)',
 'MZ': 'MECHATRONICS ENGINEERING',
 'PA': 'PLASTIC TECHNOLOGY',
 'PC': 'PETRO CHEMICAL TECHNOLOGY',
 'PD': 'PETRO CHEMICAL ENGINEERING',
 'PE': 'PETROLEUM ENGINEERING',
 'PH': 'PHARMACEUTICAL TECHNOLOGY',
 'PM': 'PHARMACEUTICAL TECHNOLOGY (SS)',
 'PN': 'PRODUCTION ENGINEERING (SS)',
 'PP': 'PETROLEUM ENGINEERING AND TECHNOLOGY (SS)',
 'PR': 'PRODUCTION ENGINEERING',
 'PS': 'PRODUCTION ENGINEERING (SANDWICH) (SS)',
 'PT': 'PRINTING AND PACKING TECHNOLOGY',
 'RA': 'ROBOTICS AND AUTOMATION (SS)',
 'RM': 'ROBOTICS AND AUTOMATION',
 'RP': 'RUBBER AND PLASTIC TECHNOLOGY',
 'SB': 'COMPUTER SCIENCE AND ENGINEERING (INTERNET OF THINGS AND CYBER SECURITY INCLUDING BLOCK CHAIN TECHNOLOGY)',
 'SC': 'COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)',
 'SE': 'INFORMATION SCIENCE AND ENGINEERING',
 'SF': 'SAFETY AND FIRE ENGINEERING',
 'TC': 'TEXTILE CHEMISTRY',
 'TS': 'COMPUTER SCIENCE AND TECHNOLOGY',
 'TT': 'TEXTILE TECHNOLOGY (SS)',
 'TX': 'TEXTILE TECHNOLOGY',
 'XC': 'CIVIL ENGINEERING (TAMIL MEDIUM)',
 'XM': 'MECHANICAL ENGINEERING (TAMIL MEDIUM)',
 'XS': 'COMPUTER SCIENCE AND ENGINEERING (TAMIL)',
 'AR': 'ARCHITECTURE',
 'BA': 'ARCHITECTURE(SS)',
 'EV': 'ELECTRONICS ENGINEERING (VLSI DESIGN AND TECHNOLOGY)',
 'EA': 'ELECTRONICS AND COMMUNICATION (ADVANCED COMMUNICATION TECHNOLOGY)',
 'ID': 'INTERIOR DESIGN(SS)',
 'EL': 'ELECTRONICS ENGINEERING(VLSI DESIGN AND TECHNOLOGY)',
 'MB': 'MECHANICAL ENGINEERING(AUTOMOBILE)',
 'DA': 'BACHELOR OF DESIGN',
 'IX': 'ELECTRONICS INSTRUMENTATION AND CONTROL ENGINEERING',
 'EX': 'ELECTRONICS AND COMPUTER ENGINEERING',
 'EF': 'ELECTRICAL AND COMPUTER ENGINNERING',
 'CK': 'CIVIL ENGINEERING(ENVIRONMENTAL ENGINEERING)',
 'MJ': 'MECHANICAL AND SMART MANUFACTURING'}

In [ ]:
df_ranklist_avg = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_RANKLIST_AVG.xlsx')

In [ ]:
df_cutoff_avg = pd.read_excel('/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/GOVT_ACADEMIC_CUTOFF_AVG.xlsx')

## üîÑ 3.8. Apply Code-Name Mapping to All Sheets
*Adding human-readable college/branch names.*

In [ ]:
def code_name_match(df):
    for index, row in df.iterrows():
        college_code = row['COLLEGE CODE']
        branch_code = row['BRANCH CODE']

        college_name = code_clg.get(college_code, 'Unknown')
        branch_name = code_branch.get(branch_code, 'Unknown')

        df.at[index, 'COLLEGE NAME'] = college_name
        df.at[index, 'BRANCH NAME'] = branch_name

    return df

In [ ]:
df_cutoff2022 = code_name_match(df_cutoff2022)
df_cutoff2023 = code_name_match(df_cutoff2023)
df_cutoff2024 = code_name_match(df_cutoff2024)

df_ranklist2022 = code_name_match(df_ranklist2022)
df_ranklist2023 = code_name_match(df_ranklist2023)
df_ranklist2024 = code_name_match(df_ranklist2024)

In [ ]:
df_ranklist_avg = code_name_match(df_ranklist_avg)
df_cutoff_avg = code_name_match(df_cutoff_avg)

## üîÑ 3.9. Fill Missing College Names from Custom Dictionary
*Fixing unmatched college names.*

In [ ]:
# Path to the consolidated Excel file
file_path = "/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx"

# Read each sheet into separate DataFrames
df_cutoff2022 = pd.read_excel(file_path, sheet_name="Cutoff_2022")
df_cutoff2023 = pd.read_excel(file_path, sheet_name="Cutoff_2023")
df_cutoff2024 = pd.read_excel(file_path, sheet_name="Cutoff_2024")
df_ranklist2022 = pd.read_excel(file_path, sheet_name="Ranklist_2022")
df_ranklist2023 = pd.read_excel(file_path, sheet_name="Ranklist_2023")
df_ranklist2024 = pd.read_excel(file_path, sheet_name="Ranklist_2024")
df_cutoff_avg = pd.read_excel(file_path, sheet_name="Avg_Cutoff")
df_ranklist_avg = pd.read_excel(file_path, sheet_name="Avg_Rank")

In [ ]:
# Mapping dictionary
college_name_map = {
    2314: 'Muthayammal College of Engineering, Kakkaveri Post, Namakkal District 637408',
    2328: 'K S R Institute for Engineering and Technology (Autonomous) Thokkavadi Namakkal District 637215',
    2378: 'Cherraan College of Technology, Cheran Nagar, Thittuparai, Kangeyam,  Tiruppur, Tamil Nadu ‚Äì 638 701.',
    2606: 'Jayam College of Engineering and Technology, Nallanur Post, Dharmapuri District 636813',
    2661: 'Vivekanandha College of Technology for Women, Sathinaickenpalayam, Elayampalayam Village, Kumaramangalam, Namakkal District 637205',
    2665: 'Mahendra Institute of Engineering and Technology, Mahendrapuri, Mallasamudram, Namakkal District 637503',
    4972: 'AMRITA College of Engineering and Technology, Erachakulam Post, Kanyakumari District 629902',
    1313: 'Shree Motilal Kanhaiyalal (SMK)Fomra Institute of Technology, Old Mahabalipuram Road (OMR), Kelambakkam, Chengalpattu District 603103',
    1334: 'ARS College of Engineering, Maraimalai Nagar Post, Chengalpattu District 603209',
    3403: 'Mahalakshmi Engineering College, Trichy-Salem Highways, (Near No.1 Tollgate), Melpathu, Siruganbur Post, Tiruchirappalli District 621213',
    1398: 'Chennai Institute of Technology and Applied Research, Sarathy Nagar, Puduppair, Kundrathur, Chennnai ‚Äì 600 069.',
    3462: 'Ariyalur Engineering College, NH-227, Trichy-Chithambaram NH, Karuppur-Senapathy Post, Ariyalur District 621707',
    1533: 'Panimalar Institute Of Technology',
    3802: 'Shri Angalamman College of Engineering and Technology, Siruganoor, Tiruchirapalli-621 105',
    3809: 'Kurinji College of Engineering and Technology, Manapparai, Tiruchirappalli District 621307',
    3859: 'Sembodai Rukmani Varatharajan Engineering College, Sembodai Village, Vedaraniam, Nagappattinam District 614820'
}

# List of all your DataFrames
all_dfs = [
    df_cutoff2022, df_cutoff2023, df_cutoff2024,
    df_ranklist2022, df_ranklist2023, df_ranklist2024,
    df_cutoff_avg, df_ranklist_avg
]

# Update college names in all DataFrames
for df in all_dfs:
    mask = df['COLLEGE NAME'] == 'Unknown'
    df.loc[mask, 'COLLEGE NAME'] = df.loc[mask, 'COLLEGE CODE'].map(college_name_map).fillna('Unknown')

In [ ]:
with pd.ExcelWriter("/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/(with_all_colleges)TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx", engine='xlsxwriter') as writer:
    df_cutoff2022.to_excel(writer, sheet_name="Cutoff_2022", index=False)
    df_cutoff2023.to_excel(writer, sheet_name="Cutoff_2023", index=False)
    df_cutoff2024.to_excel(writer, sheet_name="Cutoff_2024", index=False)
    df_ranklist2022.to_excel(writer, sheet_name="Ranklist_2022", index=False)
    df_ranklist2023.to_excel(writer, sheet_name="Ranklist_2023", index=False)
    df_ranklist2024.to_excel(writer, sheet_name="Ranklist_2024", index=False)
    df_cutoff_avg.to_excel(writer, sheet_name="Avg_Cutoff", index=False)
    df_ranklist_avg.to_excel(writer, sheet_name="Avg_Rank", index=False)

In [ ]:
# list college name or branch name is Unknown
df_ranklist_avg[df_ranklist_avg['BRANCH NAME'] == 'Unknown']

Empty DataFrame
Columns: [COLLEGE CODE, BRANCH CODE, MBC, OC, BC, BCM, SC, SCA, ST, MBCDNC, MBCV, COLLEGE NAME, BRANCH NAME]
Index: []

In [ ]:
df_cutoff_avg[df_cutoff_avg['BRANCH NAME'] == 'Unknown']

Empty DataFrame
Columns: [COLLEGE CODE, BRANCH CODE, MBC, OC, BC, BCM, SC, SCA, ST, MBCDNC, MBCV, COLLEGE NAME, BRANCH NAME]
Index: []

## üß≠ 3.10. Reorder Columns Across All Sheets
Standardizing the column order.

In [ ]:
# Path to your Excel file with 8 sheets
input_file = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/(with_all_colleges)TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx'
output_file = '/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/(with_all_colleges)TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx'

# Define the desired column order
desired_order = [
    'COLLEGE CODE', 'COLLEGE NAME', 'BRANCH CODE', 'BRANCH NAME',
    'OC', 'BC', 'BCM', 'MBC', 'MBCDNC', 'MBCV', 'SC', 'SCA', 'ST'
]

# Read all sheets
sheets = pd.read_excel(input_file, sheet_name=None)

# Reorder columns for each sheet
reordered_sheets = {}
for sheet_name, df in sheets.items():
    # Ensure all columns in desired_order are present, ignore missing ones
    existing_columns = [col for col in desired_order if col in df.columns]
    other_columns = [col for col in df.columns if col not in desired_order]
    new_order = existing_columns + other_columns
    reordered_sheets[sheet_name] = df[new_order]

# Save to new Excel file
with pd.ExcelWriter(output_file, engine='xlsxwriter') as writer:
    for sheet_name, df in reordered_sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print("Reordered Excel saved as:", output_file)

Reordered Excel saved as: /content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/(with_all_colleges)TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx

# üìä 4. Data Export, Reporting & Visualization Prep
*Objective: Organize outputs for interpretation or sharing*

## üìö 4.1. Merge PDFs into One
*Combining multiple PDF outputs into one report.*

In [ ]:
!pip install pypdf

Collecting pypdf
  Downloading pypdf-5.6.0-py3-none-any.whl.metadata (7.2 kB)
Downloading pypdf-5.6.0-py3-none-any.whl (304 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 304.2/304.2 kB 3.4 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-5.6.0

In [ ]:
from pypdf import PdfWriter  # or from PyPDF2 import PdfMerger

# List of PDF file paths
pdf_files = [
    "/content/Cutoff Matrix for Government School Reservation ‚Äì 2022.pdf",
    "/content/Cutoff Matrix for Government School Reservation ‚Äì 2023.pdf",
    "/content/Cutoff Matrix for Government School Reservation ‚Äì 2024.pdf",
    "/content/Rank Matrix for Government School Reservation ‚Äì 2022.pdf",
    "/content/Rank Matrix for Government School Reservation ‚Äì 2023.pdf",
    "/content/Rank Matrix for Government School Reservation ‚Äì 2024.pdf",
    "/content/Average Cutoff Matrix for Government School Reservation.pdf",
    "/content/Average Rank Matrix for Government School Reservation.pdf"
]

# Create merger object
merger = PdfWriter()

# Append each file
for pdf in pdf_files:
    merger.append(pdf)

# Write out the merged PDF
merger.write("/content/TNEA_7_5_GovtSchool_Cutoff_Rank_Consolidated.pdf")
merger.close()

## üîñ 4.2. Add Bookmarks to Consolidated PDF
*Adding bookmarks to navigate merged PDF easily.*

In [ ]:
!pip install --upgrade PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 232.6/232.6 kB 2.5 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [ ]:
from PyPDF2 import PdfReader, PdfWriter

start_pages = [0, 75, 169, 269, 345, 439, 539, 646]  # example start pages


sheet_titles = ['CUTOFF MATRIX FOR GOVERNMENT SCHOOL RESERVATION ‚Äì 2022', 'CUTOFF MATRIX FOR GOVERNMENT SCHOOL RESERVATION ‚Äì 2023',
                'CUTOFF MATRIX FOR GOVERNMENT SCHOOL RESERVATION ‚Äì 2024', 'RANK MATRIX FOR GOVERNMENT SCHOOL RESERVATION ‚Äì 2022',
                'RANK MATRIX FOR GOVERNMENT SCHOOL RESERVATION ‚Äì 2023', 'RANK MATRIX FOR GOVERNMENT SCHOOL RESERVATION ‚Äì 2024',
                'AVERAGE CUTOFF MATRIX FOR GOVERNMENT SCHOOL RESERVATION', 'AVERAGE RANK MATRIX FOR GOVERNMENT SCHOOL RESERVATION']

# Read the source PDF
reader = PdfReader("/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/Consolidated pdf with college names/TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated.xlsx.pdf")
writer = PdfWriter()

# Add all pages to writer
for page in reader.pages:
    writer.add_page(page)

# Add bookmarks (outline items)
for title, page_number in zip(sheet_titles, start_pages):
    writer.add_outline_item(title=title, page_number=page_number)

# Save new PDF with bookmarks
with open("/content/drive/MyDrive/TNEA Govt Schl reservation cutoff/four rounds/Consolidated pdf with college names/TNEA_GovtSchool_7_5_Reservation_Cutoff_Rank_Consolidated(BM).xlsx.pdf", "wb") as f:
    writer.write(f)